In [1]:
import tensorflow as tf

In [3]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder(tf.float32, shape = [None, 4])
Y = tf.placeholder(tf.float32, shape = [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))

train = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    feed = {X: x_data, Y: y_data}
    
    for step in range(2001):
        _, cost_val = sess.run([train, cost], feed_dict = feed)
        
        if step % 200 == 0:
            print(step, cost_val)
    
    print('--------------')
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))




0 5.043433
200 0.63815415
400 0.52817327
600 0.43561852
800 0.3460143
1000 0.259212
1200 0.22205828
1400 0.20236263
1600 0.18575694
1800 0.17157544
2000 0.15933284
--------------
[[1.0790596e-02 9.8919791e-01 1.1404718e-05]] [1]
--------------
[[0.794166   0.17696035 0.02887366]] [0]
--------------
[[1.7755525e-08 3.7764927e-04 9.9962234e-01]] [2]
--------------
[[1.0790596e-02 9.8919791e-01 1.1404695e-05]
 [7.9416609e-01 1.7696027e-01 2.8873663e-02]
 [1.7755525e-08 3.7764927e-04 9.9962234e-01]] [1 0 2]
